#!/usr/bin/env python3
"""Real-time evaluation of the agent trained on the snake environment.
License:
  BSD 3-Clause License
  Copyright (c) 2023, Autonomous Robotics Club of Purdue (Purdue ARC)
  All rights reserved.
"""

from rktl_autonomy import SnakeInterface
from stable_baselines3 import PPO
from os.path import expanduser
import rclpy

# create interface (and init ROS)
env = SnakeInterface(eval=True)
node = rclpy.create_node('snake_agent')

# load the model
weights = expanduser(node.get_parameter('~weights'))
model = PPO.load(weights)

# evaluate in real-time
obs = env.reset()
while True:
    action, __ = model.predict(obs)
    try:
        obs, __, __, __ = env.step(action)
    except rclpy.ROSInterruptException:
        exit()
