/**:
  ros__parameters:
    rate: 10.0
    supersampling: 2
    publish_particles: true
    num_particles: 100
    resample_proportion: 0.05
    boundary_check: true
    delay:
      compensate: true
      duration: 0.1
    allowable_latency: 1.25
    open_loop_limit: 10
    measurement_error:
      location: 0.1
      orientation: 0.2
    generator_noise:
      location: 0.5
      orientation: 0.75
      velocity: 0.1
      steering_angle: 0.05
    efforts:
      enable: true
      buffer_size: 15
      throttle:
        noise: 0.2
        max:  1.0
        min: -1.0
      steering:
        noise: 0.2
        max:  1.0
        min: -1.0