#!/usr/bin/env python3
"""Create a depth map to project camera data onto ground plane
License:
  BSD 3-Clause License
  Copyright (c) 2022, Autonomous Robotics Club of Purdue (Purdue ARC)
  All rights reserved.
"""

# ROS
import rospy
from sensor_msgs.msg import Image, CameraInfo
from tf2_ros import Buffer, TransformListener
from tf.transformations import translation_matrix, quaternion_matrix

import numpy as np

class Projector(object):
    """Class to synchronize and buffer all poses."""
    def __init__(self):
        rospy.init_node('projector')
        self.depth_pub = rospy.Publisher('depth_rect', Image, queue_size=1)
        rospy.Subscriber('camera_info', CameraInfo, self.camera_info_cb)

        # used to access TF tree
        buffer = Buffer()
        TransformListener(buffer)

        # variables that are needed from camera_info
        self.initialized = False
        self.frame_id = None
        self.width = None
        self.height = None
        self.cam_to_img = None

        # variables that are needed from main loop
        self.img_msg = None

        # rate at which to re-compute depth map
        rate = rospy.Rate(1.0/rospy.get_param('~update_period', 1))

        # compute depth map in main loop and cache since it is slow changing
        # publish latest in callback so that the stamps match (for rviz)
        while not rospy.is_shutdown():
            # check if camera_info callback has been run
            if not self.initialized:
                continue

            # get camera location via TF tree
            try:
                map_to_cam_msg = buffer.lookup_transform('map', self.frame_id, rospy.Time())
            except:
                continue

            # pull translation and quaternion from pose msg
            translation = np.array([
                map_to_cam_msg.transform.translation.x,
                map_to_cam_msg.transform.translation.y,
                map_to_cam_msg.transform.translation.z])
            quaternion = np.array([
                map_to_cam_msg.transform.rotation.x,
                map_to_cam_msg.transform.rotation.y,
                map_to_cam_msg.transform.rotation.z,
                map_to_cam_msg.transform.rotation.w])
            # create homographic matrix
            map_to_cam = translation_matrix(translation) @ quaternion_matrix(quaternion)

            # ground plane in map space (X direction, Y direction, origin point)
            # any [a,b,1].T input results in a point on the ground plane
            ground_plane = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1]]).T

            # depth * [i,j,1].T = cam_to_img x map_to_cam x ground_plane x [a,b,1].T
            # [i,j,1].T = cam_to_img x map_to_cam x ground_plane x [A,B,1/depth].T

            # create matrix of all pixels
            w = self.width
            h = self.height
            i = np.arange(stop=w).reshape((w,1,1,1))
            j = np.arange(stop=h).reshape((1,h,1,1))

            i = np.broadcast_to(i, (w,h,1,1))
            j = np.broadcast_to(j, (w,h,1,1))
            k = np.broadcast_to(1, (w,h,1,1))

            img = np.concatenate((i,j,k), axis=2)

            # reshape matrix
            mat = (self.cam_to_img @ map_to_cam @ ground_plane).reshape((1,1,3,3))
            mat = np.broadcast_to(mat, (w,h,3,3))

            # solve for all pixels at once
            depth = np.linalg.solve(mat, img)
            # extract depth
            depth = 1.0/(depth[:,:,2,0].reshape((w,h)))

            # create message
            if self.img_msg is None:
                self.img_msg = Image()
                self.img_msg.header.frame_id = self.frame_id
                self.img_msg.height = h
                self.img_msg.width = w
                self.img_msg.encoding = '32FC1'
                self.img_msg.step = 4*w
            self.img_msg.data = depth.astype('float32').tobytes()

            # delay since making the depth map is expensive
            rate.sleep()

    def camera_info_cb(self, info_msg):
        """Callback for publishing depth map"""
        # extract relevant data if first time
        if not self.initialized:
            self.frame_id = info_msg.header.frame_id
            self.width = info_msg.width
            self.height = info_msg.height
            self.cam_to_img = np.array(info_msg.P).reshape((3,4))
            self.initialized = True

        # publish latest depth map
        if self.img_msg is not None:
            self.img_msg.header.stamp = info_msg.header.stamp
            self.depth_pub.publish(self.img_msg)

if __name__ == "__main__":
    Projector()