#!/usr/bin/env python3
"""Use joystick data to control car in sim.
License:
  BSD 3-Clause License
  Copyright (c) 2020, Autonomous Robotics Club of Purdue (Purdue ARC)
  All rights reserved.
"""

import rospy
from rktl_msgs.msg import ControlEffort
from std_srvs.srv import Empty
from sensor_msgs.msg import Joy

def callback(joy):
    msg = ControlEffort()
    msg.header.stamp = rospy.Time.now()
    if (joy.buttons[6] == 1):
        reset_srv.call()
    else:
        msg.throttle = (joy.axes[5] - joy.axes[2]) / 2
        msg.steering = joy.axes[0]
    effort_pub.publish(msg)

rospy.init_node('xbox')
effort_pub = rospy.Publisher('effort', ControlEffort, queue_size=1)
reset_srv = rospy.ServiceProxy('/sim_reset', Empty)
rospy.Subscriber('joy', Joy, callback)
rospy.spin()