#!/usr/bin/env python3
"""Real-time evaluation of the agent trained for the Rocket League project.
License:
  BSD 3-Clause License
  Copyright (c) 2022, Autonomous Robotics Club of Purdue (Purdue ARC)
  All rights reserved.
"""

from rktl_autonomy import RocketLeagueInterface
from stable_baselines3 import PPO
from os.path import expanduser
import rospy

# Create interface (and init ROS).
env = RocketLeagueInterface(eval=True)

# Load the model.
weights = expanduser(rospy.get_param('~weights'))
model = PPO.load(weights)

# Evaluate in real-time.
obs = env.reset()
while True:
    # Predict the future action for the sim.
    action, __ = model.predict(obs)
    try:
        # Step the sim with the action from the model.
        obs, __, __, __ = env.step(action)
    except rospy.ROSInterruptException:
        exit()
