#!/usr/bin/env python3
"""Real-time evaluation of the agent trained for the Rocket League project.
License:
  BSD 3-Clause License
  Copyright (c) 2022, Autonomous Robotics Club of Purdue (Purdue ARC)
  All rights reserved.
"""

from rktl_autonomy import RocketLeagueInterface
from stable_baselines3 import PPO
from os.path import expanduser
import rospy
"""
overview:
Load the weights for the specify model (PPO in this case)
Create instance of the rocket_league_interface
Reset the model for the rocket_league_interface
Crete a PPO model based off the weights
Infinite loop: 
- predict the action based of the model
- get the observation
- step the action for the specific step based on the action 
"""
# create interface (and init ROS)
env = RocketLeagueInterface(eval=True)

# load the model
weights = expanduser(rospy.get_param('~weights'))
model = PPO.load(weights)

# evaluate in real-time
obs = env.reset()
while True:
    action, __ = model.predict(obs)
    try:
        obs, __, __, __ = env.step(action)
    except rospy.ROSInterruptException:
        exit()
