#!/usr/bin/env python3
"""Use ball location to determine when a goal is scored.
License:
  BSD 3-Clause License
  Copyright (c) 2020, Autonomous Robotics Club of Purdue (Purdue ARC)
  All rights reserved.
"""



# ROS
import rospy
from std_msgs.msg import Bool, Uint16, Int8, Odometry
from rktl_msgs.msg import Score, MatchStatus

class ScoreKeeper():
    def __init__(self):
        rospy.init_node('score_keeper')

        self.orange_score = 0
        self.blue_score = 0
        self.orange_goal = (rospy.get_param('/field/length', 1) + 0.1) / 2 
        self.blue_goal = (rospy.get_param('/field/length', 1)  + 0.1) / -2
        self.enabled = False
        self.match_status = Int8(0)
        self.game_clock = Uint16(0)

        # Publishers
        # self.score_pub = rospy.Publisher('score', Score, queue_size=1)
        # self.active_pub = rospy.Publisher('cars/enable', Bool, queue_size=1)
        # self.game_clock_pub = rospy.Publisher('game_clock', Int8, queue_size=1)
        self.match_status_pub = rospy.Publisher('match_status', MatchStatus, queue_size=1)
        
        # Subscribers
        rospy.Subscriber('ball/odom', Odometry, self.check_goal)
        rospy.Subscriber('cars/enable', Bool, self.enable)

        # main loop
        rate = rospy.Rate(10) #10hz
        while not rospy.is_shutdown():
            rate.sleep()

    def update_status(self):
        if (self.match_status == 0 and self.game_clock == 0):
            if (self.orange_score > self.blue_score):
                self.match_status = Int8(3)
            else:
                self.match_status = Int8(4)
        score = Score(self.orange_score, self.blue_score)
        self.match_status_pub.publish(MatchStatus(self.match_status.header, self.match_status, self.game_clock, score))


    def check_goal(self, ball_pose: Odometry):
        if self.enabled:
            # Check if ball is in goal
            if ball_pose.pose.pose.position.x >= self.orange_goal:
                self.orange_score += 1
            elif ball_pose.pose.pose.position.x <= self.blue_goal:
                self.blue_score += 1
            self.score_pub.publish(Score(ball_pose.header, self.orange_score, self.blue_score))
            self.active_pub.publish(False)
            self.enabled = False

    def enable(self, data: Bool):
        # enable after a goal is scored & cars are replaced
        if data.data:
            self.enabled = True

if __name__ == "__main__":
    ScoreKeeper()