#!/usr/bin/env python

"""Publishes simple paths to the network.

License:
  BSD 3-Clause License
  Copyright (c) 2020, Autonomous Robotics Club of Purdue (Purdue ARC)
  All rights reserved.
  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:
  1. Redistributions of source code must retain the above copyright notice, this
     list of conditions and the following disclaimer.
  2. Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation
     and/or other materials provided with the distribution.
  3. Neither the name of the copyright holder nor the names of its
     contributors may be used to endorse or promote products derived from
     this software without specific prior written permission.
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

#3rd party modules
import rospy
import numpy as np
from std_msgs.msg import Float64
from geometry_msgs.msg import Twist, Pose, PoseArray
from std_srvs.srv import Empty, EmptyResponse
from nav_msgs.msg import Odometry

# Local modules
import local_planner.convert as convert

class SimplePathPublisherROS(object):
    def __init__(self):
        rospy.init_node('simple_path_publisher')

        self.bot_pos = None
        self.frame_id = rospy.get_param('~frame_id', 'map')

        # Publishers
        self.path = rospy.Publisher('bot_path', PoseArray)
        self.final_speed = rospy.Publisher('bot_final_speed', Float64)

        # Subscribers
        rospy.Subscriber('bot_odom', Odometry, self.odom_cb)

        # Services
        rospy.Service('publish_simple_path', Empty, self.publish_simple_path)

        rospy.spin()

    def odom_cb(self, odom_msg):
        self.bot_pos, self.bot_orientation, _ = convert.pose_covar_to_array(odom_msg.pose)

    def publish_simple_path(self, _):
        path_msg = PoseArray()
        path_msg.header.frame_id = self.frame_id

        bot_dir = 

        pose = Pose()
        position = (self.bot_pos / (np.linalg.norm(self.bot_pos))) + self.bot_pos
        pose.position.x = position[0]
        pose.position.y = position[1]
        pose.orientation.x = self.bot_orientation[0]
        pose.orientation.y = self.bot_orientation[1]
        pose.orientation.z = self.bot_orientation[2]
        pose.orientation.w = self.bot_orientation[3]
        path_msg.poses.append(pose)

        pose = Pose()
        position = (self.bot_pos / (np.linalg.norm(self.bot_pos))) * 1.5 + self.bot_pos
        pose.position.x = position[0]
        pose.position.y = position[1]
        pose.orientation.x = self.bot_orientation[0]
        pose.orientation.y = self.bot_orientation[1]
        pose.orientation.z = self.bot_orientation[2]
        pose.orientation.w = self.bot_orientation[3]
        path_msg.poses.append(pose)

        final_speed_msg = Float64(0.25)
        self.path.publish(path_msg)
        self.final_speed.publish(final_speed_msg)
        return EmptyResponse()

if __name__ == '__main__':
    try:
        SimplePathPublisherROS()
    except rospy.ROSInterruptException:
        pass