#!/usr/bin/env python3
"""Contains the SimpleDriveROS Node.
License:
  BSD 3-Clause License
  Copyright (c) 2020, Autonomous Robotics Club of Purdue (Purdue ARC)
  All rights reserved.
"""

# 3rd party modules
import rospy
from geometry_msgs.msg import Twist
from nav_msgs.msg import Odometry


class SimpleDriveROS(object):
    """A node to drive the car in a simple fashion."""

    def __init__(self):
        rospy.init_node('simple_drive_node')

        self.path_start_time = None
        self.path = None
        self.last_pose_idx = None
        self.final_speed = None

        self.frame_id = rospy.get_param('~frame_id', 'map')

        # Publishers
        self.bot_velocity_cmd = rospy.Publisher('car0/velocity',
                                                Twist, queue_size=1)

        # Subscribers
        rospy.Subscriber('car0/odom', Odometry, self.odom_cb)

        rospy.spin()

    def odom_cb(self, odom_msg):
        """Tells car to drive forwards in a circle."""

        # Publish command data
        twist = Twist()

        twist.linear.x = -0.1
        twist.angular.z = 0.2
        self.bot_velocity_cmd.publish(twist)


if __name__ == "__main__":
    SimpleDriveROS()
