#!/usr/bin/env python
"""Node to run the racersim with ROS bindings.
License:
  BSD 3-Clause License
  Copyright (c) 2020, Autonomous Robotics Club of Purdue (Purdue ARC)
  All rights reserved.
  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:
  1. Redistributions of source code must retain the above copyright notice, this
     list of conditions and the following disclaimer.
  2. Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation
     and/or other materials provided with the distribution.
  3. Neither the name of the copyright holder nor the names of its
     contributors may be used to endorse or promote products derived from
     this software without specific prior written permission.
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

# 3rd party modules
from threading import Lock
import rospy
from nav_msgs.msg import Odometry
from std_srvs.srv import Empty, EmptyResponse


# Local library
import racersim
from geometry_msgs.msg import Twist, PoseWithCovarianceStamped
from rocket_league_msgs.msg import Target, Path, PathError, Waypoint


class RacerSimROS(object):
    """ROS wrapper for the racer sim."""

    def __init__(self):
        rospy.init_node('sim_node')

        self.sim = racersim.Sim(
            renderEnabled=rospy.get_param('~render/enabled', True),
            velIters=rospy.get_param('~render/velIters', 6),
            posIters=rospy.get_param('~render/posIters', 2),
            bounds=rospy.get_param('~world/bounds', 1.5),
            scaling=rospy.get_param('~render/scaling', 500)
        )

        self.lock = Lock()
        self.last_command = None
        self.last_time = None
        self.path = None
        self.lookahead = [0, 0]
        self.path_points = [[0,0]]

        self.frame_id = rospy.get_param('~frame_id', 'map')
        self.timeout = rospy.get_param('~timeout', 1.0) # Seconds
        rate = rospy.Rate(rospy.get_param('~rate', 45)) # Hz

        # Publishers
        self.ball_pub = rospy.Publisher('ball/odom', \
             Odometry, queue_size=1)
        self.bot_pub = rospy.Publisher('car0/odom', Odometry, queue_size=1)
        #self.goal_pub = rospy.Publisher('goal_pose', \
         #    PoseWithCovarianceStamped, queue_size=1)

        # Subscribers
        rospy.Subscriber('car0/velocity', Twist, self.command_cb)
        rospy.Subscriber('car0/path', Path, self.path_arr_cb)
        rospy.Subscriber('car0/lookahead_pnt', PoseWithCovarianceStamped, self.lookahead_cb)

        # Services
        rospy.Service('sim_reset', Empty, self.reset_cb)

        while not rospy.is_shutdown():
            self.loop_once()
            try:
                rate.sleep()
            except rospy.ROSInterruptException:
                pass

    def reset_cb(self, _):
        """Resets simulator."""
        self.lock.acquire()
        self.sim.reset()
        self.last_command = None
        self.last_time = None
        self.lock.release()
        return EmptyResponse()

    def path_arr_cb(self, path_arr_msg):
        """Callback for path array messages."""
        self.path = path_arr_msg.waypoint
        self.path_points = []

	for point in self.path:
		x = point.pose.position.x
		y = point.pose.position.y
		self.path_points.append([x, y])

	if self.path_points is None:
		self.path_points = [[0, 0]]

    def lookahead_cb(self, pose_msg):
        """Callback for lookahead_pnt messages."""
        x = pose_msg.pose.pose.position.x
        y = pose_msg.pose.pose.position.y
        self.lookahead = [x, y]
        #Convert x, y to whatever the sim uses

    def command_cb(self, command_msg):
        """Callback for command messages."""
        # Put this all in one tuple so that it is atomic
        self.last_command = (command_msg.linear, command_msg.angular)

    def loop_once(self):
        """Main loop."""
        self.lock.acquire()
        now = rospy.Time.now()

        if self.last_time is not None:
            # Iterate sim one step
            delta_t = (now - self.last_time).to_sec()

            if self.last_command != None:
                linear, angular = self.last_command
            else:
                empty = Twist()
                linear = empty.linear
                angular = empty.angular

            self.sim.step(linear, angular, delta_t)
            self.sim.render_path(self.path)

            # Publish ball odometry
            ball_msg = Odometry()
            ball_msg.header.stamp = now
            ball_msg.header.frame_id = self.frame_id
            ball_point = self.sim.ball.getPoint()
            ball_msg.pose.pose.position.x = ball_point[1]
            ball_msg.pose.pose.position.y = -ball_point[0]
            ball_quat = self.sim.ball.getQuaternion()
            ball_msg.pose.pose.orientation.z = ball_quat[2]
            ball_msg.pose.pose.orientation.w = ball_quat[3]
            ball_linear = self.sim.ball.body.linearVelocity
            ball_msg.twist.twist.linear.x = ball_linear[0]
            ball_msg.twist.twist.linear.y = ball_linear[1]
            ball_angular = self.sim.ball.body.angularVelocity
            ball_msg.twist.twist.angular.z = ball_angular
            self.ball_pub.publish(ball_msg)

            # Publish bot odometry
            bot_msg = Odometry()
            bot_msg.header.stamp = now
            bot_msg.header.frame_id = self.frame_id
            bot_point = self.sim.car.getPoint()
            bot_msg.pose.pose.position.x = bot_point[1]
            bot_msg.pose.pose.position.y = -bot_point[0]
            bot_quat = self.sim.car.getQuaternion()
            bot_msg.pose.pose.orientation.z = bot_quat[2]
            bot_msg.pose.pose.orientation.w = bot_quat[3]
            linear = self.sim.car.body.linearVelocity
            bot_msg.twist.twist.linear.x = linear[0]
            bot_msg.twist.twist.linear.y = linear[1]
            angular = self.sim.car.body.angularVelocity
            bot_msg.twist.twist.angular.z = angular
            self.bot_pub.publish(bot_msg)

            #Update the lookahead point
            self.sim.lookahead = self.lookahead

	    #Update the path points
	    self.sim.path_points = self.path_points

        self.last_time = now
        self.lock.release()

if __name__ == "__main__":
    RacerSimROS()
