#!/usr/bin/env python3
"""Tests control of the car matches expected model.
License:
  BSD 3-Clause License
  Copyright (c) 2020, Autonomous Robotics Club of Purdue (Purdue ARC)
  All rights reserved.
"""

import unittest
import rospy
import sys
import time
from nav_msgs.msg import Odometry
from std_msgs.msg import *
from std_srvs.srv import Empty

class TestCar(unittest.TestCase):
  sim_reset = None
  pos = 0.0
  throttle_pub = None

  @classmethod
  def setUpClass(cls):
    rospy.init_node('test_car_node')

    rospy.wait_for_service('sim_reset')
    cls.sim_reset = rospy.ServiceProxy('sim_reset', Empty)
  
    rospy.Subscriber('car0/odom', Odometry, cls.car_odom_cb)
    rospy.wait_for_message('car0/odom', Odometry)

    cls.throttle_pub = rospy.Publisher('effort/throttle',
      Float32, latch=True)

  def car_odom_cb(self, msg):
    self.pos = msg.pose.pose.position.x

  def test_throttle_resp_1(self):
    try:
      self.sim_reset()
    except rospy.ServiceException as exc:
      self.fail('failed to reset sim')
    
    rospy.sleep(rospy.Duration.from_sec(1.0))
    self.throttle_pub.publish(Float32(0.25))
    rospy.sleep(rospy.Duration.from_sec(1.25))
    pos = self.pos
    
    self.assertLess(pos, 0.2, 'car moving too fast: ' +
      f'expected distance {0.185}, actual distance {pos}')
  
    self.assertGreater(pos, 0.18, f'car moving too slow: ' +
      f'expected distance {0.185}, actual distance {pos}')

if __name__ == '__main__':
  import rostest
  rostest.run('rktl_sim', 'test_car_node', TestCar)