#!/usr/bin/env python
"""Very simple node to estimate odometry from poses over time.
License:
  BSD 3-Clause License
  Copyright (c) 2020, Autonomous Robotics Club of Purdue (Purdue ARC)
  All rights reserved.
  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:
  1. Redistributions of source code must retain the above copyright notice, this
     list of conditions and the following disclaimer.
  2. Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation
     and/or other materials provided with the distribution.
  3. Neither the name of the copyright holder nor the names of its
     contributors may be used to endorse or promote products derived from
     this software without specific prior written permission.
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

# Python
from math import sin, cos, pi
from scipy import signal

# ROS
import rospy
from geometry_msgs.msg import PoseWithCovarianceStamped
from nav_msgs.msg import Odometry
from tf.transformations import euler_from_quaternion

class OdomEstimator(object):
    """Simple node that derives velocity from position."""
    def __init__(self):
        rospy.init_node('pose_estimation')

        # variables to store previous pose and timestamp
        self.last_pose = None
        self.last_time = None

        self.x_filter = signal.butter(
            rospy.get_param('~filters/x/order', 1),
            2*pi*rospy.get_param('~filters/x/cutoff', 5.0),
            analog=True)
        self.y_filter = signal.butter(
            rospy.get_param('~filters/y/order', 1),
            2*pi*rospy.get_param('~filters/y/cutoff', 5.0),
            analog=True)
        self.theta_filter = signal.butter(
            rospy.get_param('~filters/theta/order', 1),
            2*pi*rospy.get_param('~filters/theta/cutoff', 5.0),
            analog=True)

        self.x_filter_z = signal.lfilter_zi(self.x_filter[0], self.x_filter[1])
        self.y_filter_z = signal.lfilter_zi(self.y_filter[0], self.y_filter[1])
        self.theta_filter_z = signal.lfilter_zi(self.theta_filter[0], self.theta_filter[1])

        # params
        self.BASE_LINK = rospy.get_param('~base_link', 'base_link')
        self.BUFFER_SIZE = rospy.get_param('~buffer_size', 3)

        # publishers
        self.odom_pub = rospy.Publisher('odom', Odometry, queue_size=1)

        # subscribers
        rospy.Subscriber('pose', PoseWithCovarianceStamped, self.pose_cb)

        rospy.spin()

    def pose_cb(self, pose_msg):
        """Callback for detection messages."""
        # extract bot position & angle
        x = pose_msg.pose.pose.position.x
        y = pose_msg.pose.pose.position.y
        quat = (pose_msg.pose.pose.orientation.x,
                pose_msg.pose.pose.orientation.y,
                pose_msg.pose.pose.orientation.z,
                pose_msg.pose.pose.orientation.w)
        (__, __, theta) = euler_from_quaternion(quat)

        # publish odom if there is a previous timestamp
        if self.last_time is not None:
            # create new odometry message
            odom_msg = Odometry()
            odom_msg.header = pose_msg.header
            odom_msg.child_frame_id = self.BASE_LINK
            odom_msg.pose = pose_msg.pose

            # deltas in world frame
            dx = x - self.last_pose[0]
            dy = y - self.last_pose[1]
            d_theta = theta - self.last_pose[2]

            # velocities in world frame
            dt = (pose_msg.header.stamp - self.last_time).to_sec()
            vx = dx / dt
            vy = dy / dt
            v_theta = d_theta / dt

            # velocites in local frame
            vx_local =  dx*cos(theta) + dy*sin(theta)
            vy_local = -dx*sin(theta) + dy*cos(theta)

            # add to low pass filter
            vx_local_filtered, self.x_filter_z = signal.lfilter(self.x_filter[0], self.x_filter[1], vx_local, zi=self.x_filter_z)
            vy_local_filtered, self.y_filter_z = signal.lfilter(self.y_filter[0], self.y_filter[1], vy_local, zi=self.y_filter_z)
            v_theta_local_filtered, self.theta_filter_z = signal.lfilter(self.theta_filter[0], self.theta_filter[1], v_theta, zi=self.theta_filter_z)

            # set odom velocities
            odom_msg.twist.twist.linear.x = vx_local_filtered
            odom_msg.twist.twist.linear.y = vy_local_filtered
            odom_msg.twist.twist.angular.z = v_theta_local_filtered

            # publish odom message
            self.odom_pub.publish(odom_msg)

        # reset last pose and timestamp
        self.last_time = pose_msg.header.stamp
        self.last_pose = (x, y, theta)

if __name__ == "__main__":
    OdomEstimator()
