name: Re-usable Docker Build

env:
  IMAGE_NAME: purduearc/rocket-league
  REGISTRY: ghcr.io

on:
  workflow_call:
    inputs:
      tag:
        default: "latest"
        required: false
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (tag)
        if: inputs.tag != 'latest'
        uses: docker/build-push-action@v4
        with:
          tags: ${{ env.IMAGE_NAME }}:${{ inputs.tag }}
          cache-from: type=registry,ref=${{ env.REPO_NAME }}:cache
          push: true
          context: ./docker
      - name: Build and push (latest)
        if: inputs.tag == 'latest'
        uses: docker/build-push-action@v4
        with:
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:cache,mode=max
          push: true
          context: ./docker
